name: Render Report
on: push
jobs:
  render-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - run: typst compile cee492_report.typ cee492_report.pdf
      - uses: actions/upload-artifact@v4
        with:
            name: report
            path: cee492_report.pdf
      - name: Add artifact link to summary
        run: |
            echo "### 📄 Generated PDF" >> $GITHUB_STEP_SUMMARY
            echo "[Download PDF here](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts)" >> $GITHUB_STEP_SUMMARY